version: '3.8'

services:
  database: 
    image: bitnami/postgresql:latest
    restart: always
    tty: true
    env_file: ".env"
    ports:
      - 5454:5432  # Remove this on production
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD= "trust"
      - POSTGRESQL_POSTGRES_PASSWORD= ${DATABASE_PASSWORD}
    user: root
    volumes:
      - ./database:/bitnami/postgresql
  app:
    links:
      - database
    env_file: ".env"
    build: .
    tty: true
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - .:/src